### ISSUE TITLE
E-WC-21 error sandbox User authentication failed due to invalid authentication values.

### ISSUE THREAD

**Issue by matinict** [PowerSync/TNW_AuthorizeCim#27]
Hi, 
Any One can Help me or suggest me below error .

I got error E-WC-21 error sandbox User authentication failed due to invalid authentication values.

chrome console  :
https://apitest.authorize.net/xml/v1/request.api 

{"messages":{"resultCode":"Error","message":[{"code":"E00007","text":"User authentication failed due to invalid authentication values."}]}}

My   magento version 2.2.8

**Comment by technweb** [comment]
@matinict it looks like you token+secret are incorrect, are you able to authenticate with the same credentials via a postman or some other software?

**Comment by matinict** [comment]
> @matinict it looks like you token+secret are incorrect, are you able to authenticate with the same credentials via a postman or some other software?

thanks can u provide me api doc link

**Comment by technweb** [comment]
Sure, here you go. Let me know what you discover: https://developer.authorize.net/api/reference/#gettingstarted-section-section-header

**Comment by matinict** [comment]
> Sure, here you go. Let me know what you discover: https://developer.authorize.net/api/reference/#gettingstarted-section-section-header

My sandbox: 
API Login ID: | 5QrgZ64zCs
trkey: 7dwk8G74b94a7VSs

**Comment by matinict** [comment]
issue solved after crerate setting ==> Manage Public Client Key==> new key @technweb thanks

**Comment by matinict** [comment]
After submitted my order nothing happen Disabled Place order , I check chrome debug =>network https://apitest.authorize.net/xml/v1/request.api   Response is {"opaqueData":{"dataDescriptor":"COMMON.ACCEPT.INAPP.PAYMENT","dataValue":"eyJjb2RlIjoiNTBfMl8wNjAwMDUzQThDRDlEMjZDRDYxOTE5NERDQ0Q4MUI5MkQ5RUVBRTBFNTkzQTY1OTZGMkRBMDUwRTkxOEI3RDQ5NDcxNjZEQTM4MTUyMjk0NTkxMDlCNzg0MUNDMDlEQUZBNzAyNUM5IiwidG9rZW4iOiI5NTgyNDUzMTA0MTAzMTUxNTA0NjAxIiwidiI6IjEuMSJ9"},"messages":{"resultCode":"Ok","message":[{"code":"I00001","text":"Successful."}]}}    Anything wrong?

**Comment by technweb** [comment]
@matinict open a new issue, please. Let's keep the authentication issue resolved and closed.
